ModelTC/LightLLM

lightllm/models/llama/layer_weights/hf_load_utils.py, lightllm/models/llama2/layer_weights/hf_load_utils.py
support safetensors for llama && llama2, compatable with original pytorch format, tested with llama2-7b-hf (w/ w/o safetensors)
cc @XHPlus
=> [feat]: support safetensors for llama && llama2

API_SERVER_ARGS.md, README.md, docs/ApiServerArgs.md
Usage instructions for the server parameter
=> Usage instructions for the server parameter

Dockerfile
IIUC you want to install the library itself in the Dockerfile too?
=> Install lightllm in dockerfile

lightllm/server/api_server.py, lightllm/server/httpserver/manager.py, lightllm/server/router/req_queue.py
api server args batch_max_tokens auto set value, To avoid the problem of a program getting stuck
=> api server args batch_max_tokens auto set value, To avoid the problem of a program getting stuck

lightllm/models/llama/layer_infer/model.py, lightllm/models/llama2/layer_infer/model.py
This Pull Request aims to introduce the Positional Interpolation (PI) feature to the lightllm. Positional Interpolation is a novel encoding technique that enhances the effects of Rotary Position Encoding (RoPE) by providing more precise positional information. The code now supports [long-context models](https://huggingface.co/lmsys/vicuna-7b-v1.5-16k).
Try with:
~~~bash
python -m lightllm.server.api_server --model_dir /path/to/lmsys--vicuna-7b-v1.5-16k --max_total_token_num 12000
~~~
=> Implementation of Positional Interpolation (PI) Feature

lightllm/common/configs/config.py, lightllm/server/api_server.py, lightllm/server/router/model_infer/model_rpc.py, lightllm/utils/net_utils.py
=> add nccl_port to startup args

lightllm/server/detokenization/manager.py
Fix https://github.com/ModelTC/lightllm/issues/31#issuecomment-1669504448
=> Fix garbled Chinese output

lightllm/utils/infer_utils.py, lightllm/utils/net_utils.py
Format the code and more readable by running `cd lightllm && black utils`. This PR won't break anything.
=> Uniform code style for utils for better readability

lightllm/models/llama/model.py
According to [Huggingface Transformers CodeLlama PR](https://github.com/huggingface/transformers/pull/25740), an additional parameter `rope_theta` is added to llama models, which is the base of position embedding.
=> [Support to CodeLlama] Add `rope_theta` to llama models

lightllm/models/llama_multimodal/infer_struct.py, lightllm/models/llama_multimodal/layer_infer/pre_layer_infer.py, lightllm/models/llama_multimodal/model.py, test/model/model_infer_multimodal.py, test/model/test_llama_multimodal.py
Support Llama Multimodal with repad embedding mode
=> Support Llama Multimodal

lightllm/common/basemodel/basemodel.py, lightllm/common/basemodel/layer_weights/base_layer_weight.py, lightllm/common/basemodel/layer_weights/hf_load_utils.py, lightllm/models/baichuan13b/model.py, lightllm/models/baichuan7b/model.py, lightllm/models/bloom/layer_weights/hf_load_utils.py, lightllm/models/bloom/model.py, lightllm/models/chatglm2/model.py, lightllm/models/internlm/model.py, lightllm/models/llama/layer_weights/ds_load_utils.py, lightllm/models/llama/model.py, lightllm/models/llama2/model.py, lightllm/models/qwen/model.py, lightllm/models/starcoder/model.py, lightllm/server/api_server.py, lightllm/server/router/manager.py, test/benchmark_mcq.py
add support for ds weight loading [llama], multiprocess weight loading and interface for lora weights
=> GitHub main

lightllm/server/api_server.py
=> fix bug for /v1/chat/completions

lightllm/models/qwen/layer_weights/transformer_layer_weight.py
=> fix bug for qwen tp 2 setting

lightllm/models/baichuan2_7b/layer_infer/transformer_layer_infer.py, lightllm/models/baichuan2_7b/layer_weights/pre_and_post_layer_weight.py, lightllm/models/baichuan2_7b/model.py, lightllm/server/router/model_infer/model_rpc.py
=> support Baichuan2-7b model

lightllm/models/llama/layer_infer/transformer_layer_infer.py, lightllm/models/llama/triton_kernel/flash_decoding.py, lightllm/models/llama/triton_kernel/flash_decoding_stage1.py, lightllm/models/llama/triton_kernel/flash_decoding_stage2.py, lightllm/server/api_server.py
support flashdecoding kernel.
use "--mode flashdecoding" to use.
=> [feature] llama llama2 qwen support flashdecoding kernel for long context

lightllm/models/baichuan2_13b/model.py, lightllm/server/router/model_infer/model_rpc.py
=> support Baichuan2-13b model

lightllm/models/llama/layer_infer/transformer_layer_infer.py, lightllm/models/llama/triton_kernel/splitfuse_context_flashattention_nopad.py
add splitfuse int8kv triton kernel
=> [feature]Splitfuse int8kv kernel

lightllm/common/basemodel/layer_infer/template/transformer_layer_infer_template.py, lightllm/common/basemodel/triton_kernel/destindex_copy_kv.py, lightllm/models/baichuan2_7b/layer_infer/transformer_layer_infer.py, lightllm/models/chatglm2/layer_infer/transformer_layer_infer.py, lightllm/models/chatglm2/triton_kernel/rotary_emb.py, lightllm/models/internlm/layer_infer/transformer_layer_infer.py, lightllm/models/internlm_wquant/layer_infer/transformer_layer_infer.py, lightllm/models/llama/layer_infer/transformer_layer_infer.py, lightllm/models/llama/triton_kernel/ppl_quant_copy_kv.py, lightllm/models/llama/triton_kernel/rotary_emb.py, lightllm/models/llama_awquant/layer_infer/transformer_layer_infer.py, lightllm/models/llama_wquant/layer_infer/transformer_layer_infer.py, lightllm/models/qwen/layer_infer/transformer_layer_infer.py, lightllm/models/qwen_wquant/layer_infer/transformer_layer_infer.py
=> Revert "[refactor] merge rotary_emb_fwd and destindex_copy_kv for streamlined execution"

lightllm/server/httpserver/manager.py
Fix when request << capacity, alloc too frequency, caused low throughput
=> Fix when request << capacity, alloc too frequency, caused low throughput

lightllm/server/api_server.py, lightllm/server/io_struct.py, lightllm/server/router/manager.py, lightllm/server/router/req_queue.py
(feat) Implement future-past scheduler, activate with --future_past_scheduler
=> feat: Implement future-past scheduler

lightllm/models/llama_quik/cuda_kernel/quik_awquant.py, lightllm/models/llama_quik/dev.md, lightllm/models/llama_quik/layer_infer/transformer_layer_infer.py, lightllm/models/llama_quik/layer_weights/qlinear.py, lightllm/models/llama_quik/layer_weights/transformer_layer_weight.py, lightllm/models/llama_quik/model.py, lightllm/server/router/model_infer/model_rpc.py
Support w4a4 quantization method for llama model. The quantization method is from [QUIK paper](https://arxiv.org/abs/2310.09259), and the implementation also refers to [QUIK github](https://github.com/IST-DASLab/QUIK).
=> support llama-quik, a w4a4 quantization method

lightllm/common/basemodel/layer_infer/template/transformer_layer_infer_cohere_template.py, lightllm/models/cohere/infer_struct.py, lightllm/models/cohere/layer_infer/post_layer_infer.py, lightllm/models/cohere/layer_infer/transformer_layer_infer.py, lightllm/models/cohere/layer_weights/pre_and_post_layer_weight.py, lightllm/models/cohere/layer_weights/transformer_layer_weight.py, lightllm/models/cohere/model.py, lightllm/models/cohere/splitfuse_infer_struct.py, lightllm/models/cohere/triton_kernels/layernorm.py, lightllm/server/router/model_infer/mode_backend/base_backend.py
@flyinglandlord TODO: add high performance layernorm triton kernels.
=> feat: re-impl the cohere with template

lightllm/common/mem_manager.py, lightllm/server/router/model_infer/mode_backend/base_backend.py
load llama2-7b-chat test ok.
input:
data = {
'inputs': 'San Francisco is a',
'parameters' : {
'do_sample': False,
}
}
output:
{'generated_text': ['city in Northern California that is known for its vibrant cultural scene, beautiful'], 'count_output_tokens': 16, 'finish_reason': 'length'}
=> fix mem manger get nccl_port way

README.md
=> Add `Projects using lightllm` in README.md and add `LazyLLM`

lightllm/server/httpserver/manager.py
添加日志，记录请求到达的相关信息，关联内不请求id 和 外部X-id X-session-id 等。
=> add req input log.

lightllm/server/router/model_infer/mode_backend/continues_batch/post_process.py
=> overlap post sample.

lightllm/common/quantization/vllm_quant.py, lightllm/models/vit/layer_infer/transformer_layer_infer.py, lightllm/models/vit/triton_kernel/flashattention_nopad.py
1. rmsnorm，添加单卡或者多卡优化算子逻辑
2. per_token_quant，添加激活值量化优化算子逻辑
=> perf(vit): add optimized rmsnorm and quant operator support

lightllm/common/basemodel/layer_weights/hf_load_utils.py
=> [Misc] Add a progress bar when loading the model
